<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="HomePage.aspx.cs" Inherits="Online_Book_Shopping_System.HomePage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server"> 
 <link rel="stylesheet" type="text/css" href="Styles/HomeStyle.css"/>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="homecontent">
        <h2 id="booksList">Books Available</h2>

        <div id="Panel">
            <asp:GridView ID="GridViewBook" runat="server" AutoGenerateColumns="false" DataKeyNames="BookID" AutoGenerateDeleteButton="true"
                AutoGenerateEditButton="true" OnRowCancelingEdit="GridViewBook_RowCancelingEdit"
                OnRowDeleting="GridViewBook_RowDeleting" OnRowEditing="GridViewBook_RowEditing"
                OnRowUpdating="GridViewBook_RowUpdating" CellSpacing="2">
                <Columns>
                    <asp:TemplateField HeaderText="Title">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtTitle" runat="server" Text='<%#Bind("Title") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblTitle" runat="server" Text='<%#Bind("Title") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Author">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtAuthor" runat="server" Text='<%#Bind("Author") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblAuthor" runat="server" Text='<%#Bind("Author") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                     <asp:TemplateField HeaderText="Genere">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtGenere" runat="server" Text='<%#Bind("Genere") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblGenere" runat="server" Text='<%#Bind("Genere") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                     <asp:TemplateField HeaderText="Price">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtPrice" runat="server" Text='<%#Bind("Price") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblPrice" runat="server" Text='<%#Bind("Price") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                     <asp:TemplateField HeaderText="No Of Pages">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtNoOfPages" runat="server" Text='<%#Bind("NoOfPages") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblNoOfPages" runat="server" Text='<%#Bind("NoOfPages") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <%-- <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />  
                    <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />  
                    <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />  
                    <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />  
                    <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />  
                    <SortedAscendingCellStyle BackColor="#FFF1D4" />  
                    <SortedAscendingHeaderStyle BackColor="#B95C30" />  
                    <SortedDescendingCellStyle BackColor="#F1E5CE" />  
                    <SortedDescendingHeaderStyle BackColor="#93451F" />--%>  
            </asp:GridView>
        </div>
    </div>
</asp:Content>
